### ISSUE TITLE
Underline not rendered correctly

### ISSUE THREAD

**Issue by aranvir** [asciidoctor/asciidoctor-mathematical#114]
Hi, I'm experiencing an issue when using the `\underline` command. For both, asciimath and latexmath it is rendered correctly, but when I'm generating a PDF from it, it does not work correctly. This happens for inline formulas and for blocks. In my example using asciimath, `\underline` does not work in a `[stem]` block but only for the inline formula.

PDF Rendering:
![image](https://user-images.githubusercontent.com/75439739/175260464-b0394d38-18a5-4819-93de-962d3b0ef640.png)

HTML Rendering:
![image](https://user-images.githubusercontent.com/75439739/175260588-c9fd2953-e0e0-4998-84d6-43f02242f279.png)

For document generation, I'm using the asciidoctor docker: https://hub.docker.com/r/asciidoctor/docker-asciidoctor/ (at time of writing: asciidoctor 2.0.17, asciidoctor-pdf 2.1.2, asciidoctor-mathematical 0.3.5)
For generation commands I'm using a gitlab pipeline:
```
adoc:
  stage: docs
  image: asciidoctor/docker-asciidoctor
  script:
    - asciidoctor-pdf -v
    - asciidoctor-pdf -r asciidoctor-mathematical -a mathematical-format=svg adoc/demo_asciimath.adoc
    - asciidoctor-pdf -r asciidoctor-mathematical -a mathematical-format=svg adoc/demo_latexmath.adoc
    - asciidoctor adoc/demo_asciimath.adoc
    - asciidoctor adoc/demo_latexmath.adoc
  artifacts:
    paths:
      - adoc/*.html
      - adoc/*.pdf
```

I uploaded my demo files below (adoc, html, pdf)
[adoc_math_demo.zip](https://github.com/asciidoctor/asciidoctor-mathematical/files/8965742/adoc_math_demo.zip)
